overblog_graphql:
    definitions:
        schema:
            enum: 
                query: Enum
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
