security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Document\User:
            algorithm: auto
    providers:
        mongo_provider:
            mongodb: 
                class: App\Document\User
                property: email
    firewalls:
        login:
            pattern: ^/api/auth
            stateless: true
            provider: mongo_provider
            json_login:
                check_path: /api/auth
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true

    access_control:
        - { path: ^/graphiql, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
