api_show_regions:
    path: /api/v1/regions
    controller: App\Controller\EnumDataController::getAllRegions
    methods: GET

api_show_products:
    path: /api/v1/products
    controller: App\Controller\EnumDataController::getAllProducts
    methods: GET