controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_get_rss_data:
    path: /api/v1/rss
    controller: App\Controller\RssDataController::getAllData
    methods: GET

api_get_latest_rss_data:
    path: /api/v1/rss/latest
    controller: App\Controller\RssDataController::getLatestData
    methods: GET

api_get_rss_data_by_region:
    path: /api/v1/rss/region/{region}
    controller: App\Controller\RssDataController::getItemsByRegion
    methods: GET

api_show_regions:
    path: /api/v1/regions
    controller: App\Controller\EnumDataController::getAllRegions
    methods: GET

api_show_products:
    path: /api/v1/products
    controller: App\Controller\EnumDataController::getAllProducts
    methods: GET