controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_get_rss_data:
    path: /api/v1/rss/default
    controller: App\Controller\RssDataController::getDefaultData
    methods: GET

api_login_check:
    path: /api/auth

api_register:
    path: /api/v1/register
    controller: App\Controller\AuthController::register
    methods: Post
