controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_get_rss_data:
    path: /api/v1/rss
    controller: App\Controller\RssDataController::getAllData
    methods: GET

api_show_regions:
    path: /api/v1/regions
    controller: App\Controller\EnumDataController::getAllRegions
    methods: GET
