controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

fuel_rss:
    path: /api/v1/rss
    controller: App\Controller\FuelRssController::getAllData
    methods: GET
